### ISSUE TITLE
how to edit this configuration?

### ISSUE THREAD

**Issue by a-x-** [assada/hassio-addons#2]
I even logged in to hassio: `docker exec  -it homeassistant bash`
but I cannot find any modipy.conf
2. modipy conf does not work too
3. modipy web client has no any config page

**Comment by a-x-** [comment]
I want to play sound file
I copied it to /config/sounds/file.mp3

but the service call
```
entity_id: media_player.mpd
media_content_id: /config/sounds/one-sec.mp3
media_content_type: music
```
says `file or directory not found`

<details><summary>more detailed message</summary>

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1247, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1282, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 602, in async_play_media
    ft.partial(self.play_media, media_type, media_id, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/mpd/media_player.py", line 352, in play_media
    self._client.add(media_id)
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 381, in mpd_command
    return wrapper(self, name, args, callback)
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 473, in _execute
    return retval()
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 368, in command_callback
    res = function(self, self._read_lines())
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 311, in _parse_nothing
    for line in lines:
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 538, in _read_lines
    line = self._read_line()
  File "/usr/local/lib/python3.7/site-packages/mpd/base.py", line 527, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [50@0] {add} directory or file not found
```

</details>

so I started looking up a configuration

UPD. I found some insights in https://github.com/bestlibre/hassio-addons/tree/master/mopidy, and I created /share/mopidy/media dir, but mopidy cannot play my file from it.

**Comment by a-x-** [comment]
It sees my files in the new directory, but cannot play it (I tried via this mopidy web interface and via ha service call 

![10A9027B-C6CD-42D1-8CCF-E940F4B8E61A](https://user-images.githubusercontent.com/6201068/81843229-fa297080-9555-11ea-8502-e64dbd23ab0c.jpeg)

**Comment by ps1x** [comment]
@a-x- looks like permissions issue? make sure that user that runs mopidy can access these files.
